#!/usr/bin/env python3
"""Render a separate inert-signal diagnostic and generated manuscript input.

Original Figure 5 and the parent manifest are read-only. Source/decay assumptions
are declared numerical inputs; the figure asserts no biological QS response.
"""
import argparse
import json
import subprocess
from pathlib import Path

import h5py
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
import numpy as np

from render_label_trajectory import verified_manifest, sha, xyz, snapshot, COLOURS


def render(parent, derived, output, tex_output):
    parent, derived, output, tex_output = map(Path, (parent, derived, output, tex_output))
    verified_manifest(parent)
    dm=json.loads((derived/"derived_manifest.json").read_text())
    assert sha(parent/"run_manifest.json")==dm["parent_manifest_sha256"]
    for rel,expected in dm["artifacts"].items():
        assert sha(derived/rel)==expected,rel
    assert dm["configuration"]["source_timing"]=="occupancy at MCS k held over [k,k+1)"
    metrics=json.loads((derived/"metrics.json").read_text())
    output.mkdir(parents=True,exist_ok=True)
    plt.rcParams.update({"font.size":10,"pdf.fonttype":42,"font.family":"DejaVu Sans"})
    fig=plt.figure(figsize=(11,8.3))
    gs=fig.add_gridspec(2,3,left=.07,right=.94,top=.88,bottom=.17,hspace=.4,wspace=.45)
    norm=Normalize(0,10); cmap=plt.colormaps['viridis']
    for j,t in enumerate((0,30,100)):
        species,_=snapshot(parent,t)
        with h5py.File(derived/f"fields/signal_mcs{t:06}.h5") as f:
            a=xyz(f['fields/signal']); mask=xyz(f['lattice/interior_mask']).astype(bool)
        ax=fig.add_subplot(gs[0,j],projection='3d')
        faces=ax.voxels(species>0,facecolors=cmap(norm(a)),edgecolors=(.1,.1,.1,.25),linewidth=.12,shade=False)
        for face in faces.values():face.set_rasterized(True)
        ax.set(xlim=(0,40),ylim=(0,40),zlim=(0,40));ax.set_box_aspect((1,1,1));ax.view_init(elev=25,azim=35)
        ax.set_axis_off();ax.set_title(f"({chr(97+j)}) MCS {t}")
        if t in (30,100):
            p=fig.add_subplot(gs[1,0 if t==30 else 1])
            plane=np.ma.array(a[:,:,19].T,mask=~mask[:,:,19].T)
            p.imshow(plane,origin='lower',extent=(0,40,0,40),cmap=cmap,norm=norm,interpolation='nearest')
            p.contour(species[:,:,19].T>0,levels=[.5],colors='white',linewidths=.65,origin='lower',extent=(0,40,0,40))
            p.set(title=f"({'d' if t==30 else 'e'}) z = 20, MCS {t}",xlabel="x (lattice sites)",ylabel="y (lattice sites)")
            p.set_xticks([0,20,40]);p.set_yticks([0,20,40])
    ax=fig.add_subplot(gs[1,2]);ax.plot([m['mcs'] for m in metrics],[100*m['fraction'] for m in metrics],color=COLOURS[3])
    end=metrics[-1]; first=next(m for m in metrics if m['above_threshold'])
    ax.set(xlabel="MCS",ylabel="Occupied sites above threshold (%)",xlim=(0,100),ylim=(0,100),title="(f) A ≥ 5, occupied denominator")
    ax.annotate(f"{100*end['fraction']:.1f}%\n{end['above_threshold']}/{end['occupied_sites']}",xy=(100,100*end['fraction']),xytext=(-6,14),textcoords='offset points',ha='right')
    colour_axis=fig.add_axes([.34,.55,.32,.016])
    cb=fig.colorbar(plt.cm.ScalarMappable(norm=norm,cmap=cmap),cax=colour_axis,orientation='horizontal')
    cb.set_label('A (arbitrary signal units)')
    fig.suptitle('Inert generic signal on the verified CPM trajectory',fontsize=17,y=.98)
    fig.text(.5,.935,'42 initial parcels | seed 42 | N = 40 | left-endpoint occupancy | no acceptance coupling',ha='center')
    fig.text(.5,.09,'Declared: D = 0.2 sites²/MCS; decay = 0.1/MCS; production = 1 per occupied voxel/MCS; threshold = 5.',ha='center',fontsize=10)
    fig.text(.5,.06,'Zero signal at masked walls; no flux at outer cube faces. Plane contours mark occupied sites.',ha='center',fontsize=10)
    fig.text(.5,.03,'Raster voxel faces. Computational labels and an inert field; no membrane, EPS or biological QS-response inference.',ha='center',fontsize=10)
    base=output/'fig_signal_field'
    fig.savefig(base.with_suffix('.pdf'),dpi=220);fig.savefig(base.with_suffix('.png'),dpi=180);plt.close(fig)
    subprocess.run(['pdftotext','-layout',str(base.with_suffix('.pdf')),str(base.with_suffix('.txt'))],check=True)
    receipt={ext:sha(base.with_suffix('.'+ext)) for ext in ('pdf','png','txt')}
    receipt['parent_manifest_sha256']=dm['parent_manifest_sha256'];receipt['derived_manifest_sha256']=sha(derived/'derived_manifest.json')
    base.with_suffix('.sha256').write_text(receipt['pdf']+'\n')
    base.with_suffix('.provenance.json').write_text(json.dumps(receipt,indent=2)+'\n')
    text=r'''% Generated by tools/render_signal_field.py; claim QS-INERT-01 and QS-FIG-01.
\subsection{Inert Generic Signal Diagnostic}
The verified parcel-label trajectory in Figure~\ref{fig:label_trajectory} also
drives a separate, post-hoc scalar diagnostic (Figure~\ref{fig:signal_field}).
It integrates $\partial_t A=D_A\nabla^2 A+p_s I_s-\gamma A$ with zero initial
signal, absorbing masked walls, and no flux at the outer cube faces.
Occupancy at MCS $k$ is held over $[k,k+1)$. All seven production rates are
declared numerical values of one arbitrary signal unit per occupied voxel per
MCS; $D_A=0.2$ lattice-site$^2$/MCS and $\gamma=0.1$/MCS. Euler substeps of
0.5 MCS satisfy the diffusion--decay positivity bound. No signal quantity
enters the CPM state, Hamiltonian or RNG. These inputs are not organism-specific
measurements, and no molecule, receptor, physical pitch or physical clock is assigned.

With the declared display threshold $A\geq5$, the first occupied threshold
crossing is sampled at MCS FIRSTMCS. At MCS 100 the count is NUMERATOR of
DENOMINATOR occupied interior voxels (PERCENT\%). Empty interior space remains
in the field equation but is excluded from this denominator. This is a
conditional numerical result from one frozen trajectory; it is not independent
evidence of biological quorum sensing or a coupled biological response.

\begin{figure}[htbp]
\centering
\includegraphics[width=\linewidth]{fig_signal_field}
\caption{Inert generic signal diagnostic on the same 42-founder, seed-42
parcel trajectory as Figure~\ref{fig:label_trajectory}. Top: fixed-camera
occupied voxel faces coloured by signal. Bottom: the lower central plane
($z=20$, one-based) at MCS 30 and 100, and the occupied-site threshold fraction
at all 101 saved MCS values. Plane contours denote occupied sites. The signal
also exists in empty interior voxels. Rendering uses rasterized voxel faces,
with no ray tracing. Labels and signal do not represent membranes, EPS or
biological reconstitution. Production, diffusion, decay and threshold are
declared numerical inputs, with no acceptance coupling.}
\label{fig:signal_field}
\end{figure}
'''
    text=text.replace('FIRSTMCS',str(first['mcs'])).replace('NUMERATOR',str(end['above_threshold'])).replace('DENOMINATOR',str(end['occupied_sites'])).replace('PERCENT',f"{100*end['fraction']:.1f}")
    tex_output.write_text(text)
    print(json.dumps(dict(first_crossing=first['mcs'],final=end['fraction'],figure_sha256=receipt['pdf'])))


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('parent');p.add_argument('derived');p.add_argument('output');p.add_argument('tex_output')
    render(**vars(p.parse_args()))
